import type { Metadata } from "next";
import { DM_Sans, Poppins } from "next/font/google";
import "../globals.css";
import Image from "next/image";

const DMSans = DM_Sans({
  variable: "--font-dm-sans",
  subsets: ["latin"],
});

const poppins = Poppins({
  variable: "--font-poppins",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function NoAuthLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${DMSans.variable} ${poppins.variable} antialiased`}>
        <div className="min-h-screen flex">
          <div className="flex-1 gap-12 relative flex items-center min-h-full">
            <Image
              alt="Logo do Marketplace"
              src="/images/Logo.svg"
              width={267.36}
              height={68.65}
              className="top-10 left-10 fixed"
            />
            <Image
              alt="Imagem de fundo com caixa"
              src="/images/Background.png"
              width={755}
              height={496}
            />
          </div>
          <main className="flex-1 p-6">{children}</main>
        </div>
      </body>
    </html>
  );
}
